server:
  port: 19030
  servlet:
    context-path: /code

spring:
  application:
    name: sys-code
  access:
    always-success: true
    urlPatterns:
      - /api/v1/*
    auth:
      mode: refreshToken
      tokenIgnoreUrls:
        - /favicon.ico
        - /actuator/**
        - /doc/**
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/sys-code
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    change-log: sql/changelog.yml
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.141.74:8848
