server:
  port: ${server_port:19010}
  servlet:
    context-path: /admin

spring:
  application:
    name: sys-admin
  access:
    always-success: true
    token:
      header: Authorization
      salt: admin@cowave.com
      conflict: false
      accessExpire: ${token_access_seconds:86400}
      refreshExpire: ${token_refresh_seconds:604800}
      ignoreUrls:
        - /api/v1/auth/login
        - /api/v1/auth/logon
        - /api/v1/auth/refresh
        - /api/v1/auth/register
        - /api/v1/auth/captcha
        - /api/v1/auth/captcha/email
        - /api/v1/oauth/callback/**
        - /api/v1/flow/designer/**
        - /designer/**
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${datasource_url:jdbc:postgresql://127.0.0.1:5432/sys-admin}
    username: ${datasource_username:postgres}
    password: ${datasource_password:postgres}
  liquibase:
    enabled: true
    change-log: sql/changelog.yml
  redis:
    host: ${redis_host:127.0.0.1}
    port: ${redis_port:6379}
  minio:
    endpoint: ${minio_endpoint:http://127.0.0.1:9100}
    accessKey: ${minio_accessKey:admin}
    secretKey: ${minio_secretKey:admin123}
  socket-io:
    port: ${socket_port:19011}
  mail:
    host: smtp.163.com
    username: cowaveAdmin@163.com
    password: TQQWRIRSQLTEELPT
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos_server:10.64.4.74:8848}

flowable:
  database-schema-update: true
