server:
  port: ${app_port:19000}
  servlet:
    context-path: /

spring:
  application:
    name: sys-gateway
  main:
    web-application-type: reactive
  auth:
    secret: access@cowave.com
    ignoreUrls:
      - /admin/favicon.ico
      - /admin/doc/**
      - /admin/actuator/**
      - /admin/designer/**
      - /admin/api/v1/auth/ldap
      - /admin/api/v1/auth/login
      - /admin/api/v1/auth/logon
      - /admin/api/v1/auth/refresh
      - /admin/api/v1/auth/register
      - /admin/api/v1/auth/captcha
      - /admin/api/v1/auth/captcha/email
      - /admin/api/v1/auth/callback/**
      - /admin/api/v1/flow/designer/**
      - /code/favicon.ico
      - /code/actuator/**
      - /code/doc/**
  cloud:
    discovery:
      client:
        composite-indicator:
          enabled: false
    nacos:
      discovery:
        server-addr: ${nacos_server:10.64.4.74:8848}
        metadata:
          context-path: ${server.servlet.context-path}
    gateway:
      enabled: true
      routes:
        - id: socket
          uri: lb:ws://sys-admin
          predicates:
            - Path=/socket.io/**
        - id: admin
          uri: lb://sys-admin
          predicates:
            - Path=/admin/**
        - id: quartz
          uri: lb://sys-quartz
          predicates:
            - Path=/quartz/**
        - id: flow
          uri: lb://sys-flow
          predicates:
            - Path=/flow/**
        - id: code
          uri: lb://sys-code
          predicates:
            - Path=/code/**

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
  health:
    mail:
      enabled: false
    ping:
      enabled: false
    diskSpace:
      enabled: false
    gateway:
      enabled: true
