server:
  port: 80
  servlet:
    context-path: /

spring:
  application:
    name: sys-blog
  access:
    always-success: true
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/sys-blog
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    change-log: sql/changelog.yml
  redis:
    host: 127.0.0.1
    port: 6379
  mail:
    host: smtp.163.com
    username: cowaveAdmin@163.com
    password: TQQWRIRSQLTEELPT
  thymeleaf:
    mode: HTML
    prefix: classpath:/templates/
    check-template-location: true
    suffix:  .html
    encoding: utf-8
    cache: false
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.141.74:8848

blog:
  # IP地址获取
  addressEnabled: true
  # 开启页面静态化
  pageStaticEnabled: true
  # 上传路径
  profile: public
